//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//

package au.org.cooperation.modules.base.dom.impl;

import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.apache.isis.applib.annotation.DomainObject;

import lombok.Getter;
import lombok.Setter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organisation", propOrder = { "name", "aims", "plans", "goals" })
@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Organisation {

	@XmlElement(required = true)
	@Column(allowsNull = "false")
	@Getter
	@Setter
	protected String name;

	@XmlElement()
	@Persistent(mappedBy = "organisation")
	@Getter
	protected List<Aim> aims;

	@XmlElement(required = true)
	@Persistent(mappedBy = "organisation")
	@Getter
	protected List<Plan> plans;
	
	@XmlElement(required = true)
	@Persistent(mappedBy = "organisation")
	@Getter
	protected List<Goal> goals;

	public Organisation() {
	}

	public Organisation(String name) {
		setName(name);
	}

	public Organisation addAim(String name) {
		this.getAims().add(organisationRepository.createAim(this,name));
		return this;
	}
	
	public Organisation addPlan(String name) {
		this.getPlans().add(organisationRepository.createPlan(this, name));
		return this;
	}
	
	public Organisation addGoal(String name) {
		this.getGoals().add(organisationRepository.createGoal(name));
		return this;
	}

	@XmlTransient
	@Inject
	OrganisationRepository organisationRepository;

}
