//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//


package au.org.cooperation.modules.base.dom.impl;

import java.util.List;

import javax.jdo.annotations.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.apache.isis.applib.annotation.DomainObject;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Outcome", propOrder = {
	    "description"
	})
@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Outcome {

    @XmlElement()
    @Column(allowsNull="true")
    @Getter 
    @Setter
    protected String description;
    
    @XmlTransient
    @Column(allowsNull="true")
    @Getter 
    @Setter
    protected Goal goal;
    
	@XmlTransient
	@Column(allowsNull = "true")
	@Getter
	@Setter
	private Task task;
    
    //m-n relationship
    @XmlTransient
    @Join
    @Getter
    @Setter
    protected List<Result> results;
    
	Outcome() {}

	public Outcome(String description) {
		setDescription(description);
	}

	public Outcome(Goal goal, String description) {
		setGoal(goal);
		setDescription(description);
	}
	
	public String title(){
		return getDescription().substring(0, 50);
	}
}
