//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//

package au.org.cooperation.modules.base.dom.impl;

import java.util.List;

import javax.jdo.annotations.*;

import org.apache.isis.applib.annotation.DomainObject;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Outcome {

	@Column(allowsNull = "false", name = "organisation_id")
	@Getter
	@Setter(value = AccessLevel.PRIVATE)
	private Organisation organisation;

	@Column(allowsNull = "true", length = 5000)
	@Getter
	@Setter
	protected String description;

	@Column(allowsNull = "true")
	@Getter
	@Setter(value = AccessLevel.PACKAGE)
	protected Goal goal;

	@Column(allowsNull = "true")
	@Getter
	@Setter(value = AccessLevel.PACKAGE)
	private Task task;

	// m-n relationship
	@Join
	@Getter
	@Setter(value = AccessLevel.PRIVATE)
	protected List<Result> results;

	Outcome() {
	}

	public Outcome(String description) {
		setDescription(description);
	}

	public Outcome(Organisation organisation, Goal goal, String description) {
		setOrganisation(organisation);
		setGoal(goal);
		setDescription(description);
	}

	public String title() {
		return (getDescription() != null)
				? ((getDescription().length() > 49) ? getDescription().substring(0, 50) : getDescription()) : null;
	}
}
