//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.17 at 09:22:29 PM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/OneIdSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.org.cooperation.modules.base.dom.impl;
