//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//

package au.org.cooperation.modules.base.dom.impl;

import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Order;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;

import org.apache.isis.applib.annotation.DomainObject;
import org.apache.isis.applib.annotation.ParameterLayout;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Plan {

	@Column(allowsNull = "false")
	@Getter
	@Setter(value=AccessLevel.PRIVATE)
	protected Organisation organisation;

	@Column(allowsNull = "false", length=50)
	@Getter
	@Setter
	protected String name;
	
	@Column(allowsNull = "true", length=1000)
	@Getter
	@Setter
	protected String description;

	@Persistent(mappedBy="plan")
	@Order(column="plan_goal_idx")
	@Getter
	protected List<Goal> goals;

	Plan() {
	}

	public Plan(String name) {
		setName(name);
	}
	
	public String title(){
		return getName();
	}

	public Plan(Organisation organisation, String name) {
		setOrganisation(organisation);
		setName(name);
	}
	
	public Plan addGoal(@ParameterLayout(named="Goal name") String name, @ParameterLayout(named="Primary Aim") Aim aim) {
		Goal goal = organisationRepository.createGoal(this, name, aim);
		this.getGoals().add(goal);
		this.getOrganisation().getGoals().add(goal);
		return this;
	}
	
	public List<Aim> choices1AddGoal(){
		return this.getOrganisation().getAims();
	}
	
	public String disableAddGoal(){
		if(this.getOrganisation().getAims().size() == 0)
			return "A Goal must be linked to at least one Aim, so add an Organisation Aim first";
		else
			return null;
	}
	
	@Inject
	OrganisationRepository organisationRepository;

}
