//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//

package au.org.cooperation.modules.base.dom.impl;

import java.util.Date;

import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.apache.isis.applib.annotation.DomainObject;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reward", propOrder = { "timestamp", "value", "description" })
@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Reward {
	
	@XmlTransient
	@Column(allowsNull = "false")
	@Getter
	@Setter(value = AccessLevel.PRIVATE)
	private Person person;

	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	@Column(allowsNull = "false")
	@Getter
	@Setter()
	protected Date timestamp;

	@Column(allowsNull = "true")
	@Getter
	@Setter()
	protected Float value;

	@Column(allowsNull = "true")
	@Getter
	@Setter()
	protected String description;


}
