//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//

package au.org.cooperation.modules.base.dom.impl;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Join;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;

import org.apache.isis.applib.annotation.DomainObject;
import org.apache.isis.applib.annotation.Programmatic;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Reward {

	@Column(allowsNull = "false")
	@Getter
	@Setter(value = AccessLevel.PRIVATE)
	protected Organisation organisation;

	@Column(allowsNull = "false")
	@Getter
	@Setter(value = AccessLevel.PRIVATE)
	private Person person;

	@Column(allowsNull = "false")
	@Getter
	@Setter()
	protected Date timestamp;

	@Column(allowsNull = "true")
	@Getter
	@Setter()
	protected Float value;

	@Column(allowsNull = "true")
	@Getter
	@Setter()
	protected String description;

	@Persistent(mappedBy = "reward")
	@Join()
	@Getter()
	@Setter()
	// TODO why must this be initialised???
	protected List<Effort> efforts = new ArrayList<>();

	Reward() {
	}

	public Reward(Organisation organisation, Person person) {
		setOrganisation(organisation);
		setPerson(person);
	}

	@Programmatic
	public void addEffort(Effort effort) {
		effort.setReward(this);
		this.getEfforts().add(effort);
	}
}
