//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//

package au.org.cooperation.modules.base.dom.impl;

import java.util.List;

import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;

import org.apache.isis.applib.annotation.DomainObject;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Success {

	@Column(allowsNull = "false")
	@Getter
	@Setter(value=AccessLevel.PRIVATE)
	protected Organisation organisation;

	@Column(allowsNull = "false")
	@Getter
	@Setter
	protected String name;

	@Column(allowsNull = "false")
	@Getter
	@Setter
	protected Aim aim;
	
	@Getter
	protected List<Outcome> outcome;
	
	@Getter
	protected List<Goal> goal;

	public Success() {
	}

	public Success( Organisation organisation, String name) {
		setOrganisation(organisation);
		setName(name);
	}
}
