//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//

package domainapp.modules.simple.dom.impl;

import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import org.apache.isis.applib.annotation.DomainObject;
import org.apache.isis.applib.value.DateTime;

import lombok.Getter;
import lombok.Setter;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Effort", propOrder = { "result" })
@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Effort {

	@Column(allowsNull = "false")
	@Getter
	@Setter
	private Person person;

	@Column(allowsNull = "true")
	@Getter
	@Setter
	private Task task;

	@Column(allowsNull = "true")
	@Getter
	@Setter
	private Result result;

	@Column(allowsNull = "true")
	@Getter
	@Setter
	private DateTime start;

	@Column(allowsNull = "true")
	@Getter
	@Setter
	private DateTime end;
	

	Effort() {
	}

	public Effort(Task task, Person person, DateTime start, DateTime end) {
		setPerson(person);
		setTask(task);
		setStart(start);
		setEnd(end);
	}

}
