//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.10 at 09:30:22 PM AEST 
//

package domainapp.modules.simple.dom.impl;

import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.isis.applib.annotation.DomainObject;

import lombok.Getter;
import lombok.Setter;

/**
 * <p>
 * Java class for Goal complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Goal"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="aim" type="{http://www.example.org/OneIdSchema}Aim" minOccurs="0"/&gt;
 *         &lt;element name="task" type="{http://www.example.org/OneIdSchema}Task" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="outcome" type="{http://www.example.org/OneIdSchema}Outcome" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Goal", propOrder = { "name", "aim", "tasks", "outcomes" })
@PersistenceCapable(identityType = IdentityType.DATASTORE, schema = "cooperation")
@DomainObject()
public class Goal {

	@Column(allowsNull = "true")
	@Getter
	@Setter
	protected Organisation organisation;

	@XmlElement(required = true)
	@Column(allowsNull = "false")
	@Getter
	@Setter
	protected String name;

	@Column(allowsNull = "false")
	@Getter
	@Setter
	protected Aim aim;

	@Persistent(mappedBy = "goal")
	@Getter
	protected List<Task> tasks;

	@Persistent(mappedBy = "goal")
	@Getter
	protected List<Outcome> outcomes;

	public Goal() {
	}

	public Goal(String name) {
		setName(name);
	}

	public Goal addTask(String name) {
		this.getTasks().add(taskRepository.createTask(this, name));
		return this;
	}

	public Goal addOutcome(String name) {
		this.getOutcomes().add(organisationRepository.createOutcome(this, name));
		return this;
	}

	@Inject
	OrganisationRepository organisationRepository;
	
	@Inject
	TaskRepository taskRepository;

}
